
[render]
	#The brightness of natural light.
	#Range: 0.0 ~ 1.0
	light_brightness = 0.1

[decoration]
	#The generation probability of canyons.
	#Note: If multiplayer, server-side only.
	#Range: 0.0 ~ 1.0
	canyon = 0.02
	#If true, decorate upper caves like on the overworld.
	#Note: If multiplayer, server-side only.
	ground_decoration = true
	#The generation probability of caves.
	#Note: If multiplayer, server-side only.
	#Range: 0.0 ~ 1.0
	cave = 0.2
	#The generation probability of tower dungeons.
	#Note: If multiplayer, server-side only.
	#Range: 0.0 ~ 1.0
	tower_dungeon = 0.01
	#If true, generate flat bedrock layers.
	#Note: If multiplayer, server-side only.
	flat_bedrock = false
	#The generation probability of extreme caves.
	#Note: If multiplayer, server-side only.
	#Range: 0.0 ~ 1.0
	extreme_cave = 0.15
	#The generation probability of extreme canyons.
	#Note: If multiplayer, server-side only.
	#Range: 0.0 ~ 1.0
	extreme_canyon = 0.001

[natural_spawn]
	#How many monsters must spawn.
	#Note: If multiplayer, server-side only.
	#Range: 0 ~ 5000
	max_count = 70
	#How far (in chunks) monsters must spawn.
	#Note: If multiplayer, server-side only.
	#Range: 1 ~ 10
	chunk_radius = 5
	#How high (in blocks) monsters must spawn.
	#Note: If multiplayer, server-side only.
	#Range: 10 ~ 200
	height_radius = 70
	#How far (in blocks) monsters must not spawn from players.
	#Note: If multiplayer, server-side only.
	#Range: 0 ~ 100
	safe_distance = 16
	#The spawner type of natural monsters spawn.
	#Note: If multiplayer, server-side only.
	#Allowed Values: DISABLED, VANILLA, CAVERN
	spawner_type = "CAVERN"

