
[Worldgen]
	enable_emerald_bee_nest = true
	#Range: > 0
	bottom_offset_diamond_bee_nest = 0
	#Range: > 0
	count_ender_bee_nest = 5
	#Range: > 0
	maximum_iron_bee_nest = 64
	#Range: > 0
	top_offset_emerald_bee_nest = 0
	#Range: > 0
	maximum_ender_bee_nest = 64
	#Range: > 0
	count_gold_bee_nest = 5
	#Range: > 0
	bottom_offset_redstone_bee_nest = 0
	enable_ender_bee_nest = true
	#Range: > 0
	count_lapis_bee_nest = 5
	#Range: > 0
	top_offset_iron_bee_nest = 0
	enable_redstone_bee_nest = true
	#Range: > 0
	bottom_offset_emerald_bee_nest = 0
	#Range: > 0
	bottom_offset_quartz_bee_nest = 0
	enable_quartz_bee_nest = true
	enable_diamond_bee_nest = true
	enable_iron_bee_nest = true
	enable_gold_bee_nest = true
	#Range: > 0
	count_quartz_bee_nest = 5
	#Range: > 0
	bottom_offset_lapis_bee_nest = 0
	#Range: > 0
	maximum_quartz_bee_nest = 64
	#Range: > 0
	top_offset_lapis_bee_nest = 0
	#Range: > 0
	count_redstone_bee_nest = 5
	#Range: > 0
	maximum_gold_bee_nest = 64
	#Range: > 0
	maximum_redstone_bee_nest = 64
	#Range: > 0
	bottom_offset_ender_bee_nest = 0
	#Range: > 0
	count_diamond_bee_nest = 5
	#Range: > 0
	count_iron_bee_nest = 5
	#Range: > 0
	top_offset_gold_bee_nest = 0
	#Range: > 0
	bottom_offset_iron_bee_nest = 0
	#Range: > 0
	bottom_offset_gold_bee_nest = 0
	#Range: > 0
	top_offset_ender_bee_nest = 0
	#Range: > 0
	maximum_diamond_bee_nest = 64
	#Range: > 0
	maximum_lapis_bee_nest = 64
	enable_lapis_bee_nest = true
	#Range: > 0
	top_offset_diamond_bee_nest = 0
	#Range: > 0
	top_offset_quartz_bee_nest = 0
	#Range: > 0
	count_emerald_bee_nest = 5
	#Range: > 0
	top_offset_redstone_bee_nest = 0
	#Range: > 0
	maximum_emerald_bee_nest = 64

