#If only the owner of the corpse can access the inventory
only_owner_access = true
#If everybody can access the corpse in the skeleton stage (Only if only_owner_access is set to true)
skeleton_access = false
#The time passed after a corpse despawns (only if empty)
#Range: > 20
corpse_despawn_time = 600
#The time passed after a corpse despawns even if its not empty (-1 = never)
#Range: > -1
corpse_force_despawn_time = -1
#The time passed after a corpse turns into a skeleton
#Range: > 0
corpse_skeleton_time = 72000
#If the corpse should spawn on its face
spawn_corpse_on_face = false

