
["Nasty Skeleton"]
	#Virus Distance for spreading
	#Range: 0.0 ~ 20.0
	VirusDistance = 5.0
	#Maximum Distance
	#Range: 0.0 ~ 1280000.0
	MaxDistance = 1000000.0
	#Spawn in Biome weight
	#Range: 0 ~ 200
	SpawnBiome = 50
	#Spawn in Dungeon weight
	#Range: 0 ~ 200
	SpawnDungeon = 50
	#Explosive Arrow cause Shield to drop
	ExplosiveArrowOnShield = false
	#Bonus Power
	#Range: 0 ~ 10
	BonusPower = 1
	#Maximum health
	#Range: 20.0 ~ 5000.0
	MaxHealth = 25.0
	#Spawn type based on Tempature
	SpawnTempBased = false
	#Virus Chance for spreading
	#Range: 0.0 ~ 1.0
	VirusChance = 0.02
	#Explosive Arrow cause Block to drop
	ExplosiveArrowOnBlock = true
	#Spawn light level (use 7 to be same as normal skeletons)
	#Range: 0 ~ 15
	SpawnLightLevel = 8
	#Explosive Arrow cause Armor to drop
	ExplosiveArrowOnArmor = false
	#Biome adjustments (biome,variant,hp,speed)
	BiomeAdjustments = "minecraft:plains,*,-0.2,0.2;minecraft:swamp,0,0.2,0.0;minecraft:swamp,*,0.1,-0.1;minecraft:badlands,*,0.3,0.3;minecraft:dark_forest_hills,*,0.3,0.3"
	#Bonus Power for Hard
	#Range: 0 ~ 20
	BonusHardPower = 3
	#Minimum health
	#Range: 4.0 ~ 5000.0
	MinHealth = 25.0
	#Explosive Arrow strength
	#Range: 1.0 ~ 1500.0
	ExplosiveArrowStrength = 6.0
	#Spawn weights (Green,Red,Purple,Cyan,Orange,Yellow)
	SpawnVariantWeights = "5,7,5,5,3,1"
	#Add inaccuracy to shot
	#Range: 0.0 ~ 1.0
	AddInaccuracy = 0.7
	#Minimum Distance
	#Range: 0.0 ~ 1280000.0
	MinDistance = 100000.0
	#Arrow Damage Multiplier (damage to skeleton)
	#Range: 0.0 ~ 1.0
	ArrowDamageMultiplier = 1.0
	#Spawn in Feature weight
	#Range: 0 ~ 20
	SpawnFeature = 5

["Nasty Wolf"]
	#Virus Chance for spreading
	#Range: 0.0 ~ 1.0
	VirusChance = 0.25
	#Virus Mode
	#Allowed Values: OFF, WILD, UNNAMED
	VirusMode = "WILD"

