
[miner]
	#The display type of miner status.
	#Allowed Values: HIDDEN, ACTION, HOLD, ALWAYS
	display_type = "HOLD"
	#When enabled, the miner rank name will be shown along with the miner points.
	show_rank = true
	#The display corner of miner status.
	#Allowed Values: TOP_RIGHT, TOP_LEFT, BOTTOM_RIGHT, BOTTOM_LEFT
	display_corner = "BOTTOM_RIGHT"

[dimension]
	#When true, render the cave fog.
	cave_fog = true
	#When true, play the original music for caverns.
	cave_music = true

