
[Tooltips]
	#Show Controls On Tooltips
	showControlsOnTooltips = true
	#Show Information On Tooltips
	showInfoOnTooltips = true

[WorldGen]
	#Raritanium Ore Gen
	raritaniumOreGen = true
	#Raritanium Ore Min Y
	raritaniumOreGenMinY = 0
	#Raritanium Veins Per Chunk
	raritaniumOreVeinsPerChunk = 2
	#Raritanium Ore Max Y
	raritaniumOreGenMaxY = 30
	#Raritanium Vein Size
	raritaniumVeinSize = 4

[BlockScans]
	#Vein Scan Max Size
	#The Vein Scan is a system used by Blueprints, Scaffolds and Networks.
	#It scans for blocks in a chain. The max size is how many chains will occur. Lower values run faster on servers.
	#2304 is the maximum count of blocks in a single Player inventory. There is no real reason to set it above, but the option is there
	#Range: 0 ~ 5000
	veinScanMaxSize = 2304
	#Brush Max Size
	#0 to Disable. The max size of blocks the Brush can place. Lower values run faster on servers.
	#Range: 0 ~ 10000
	worldEditMaxSize = 5000

[Economy]
	#Trading Post Currency Capacity
	#The max amount of currency the Trading Post can store.
	#Range: 0 ~ 99999999
	postCurrencyCapacity = 1000000
	#Rich Money Bag Minimum Coins Amount
	#The minimum of the random amount of currency the Rich Money Bag gives.
	#Range: 0 ~ 10000
	richMoneyBagMin = 100
	#Currency Name
	currencyName = "RC"
	#Cheap Money Bag Minimum Coins Amount
	#The minimum of the random amount of currency the Cheap Money Bag gives.
	#Range: 0 ~ 10000
	cheapMoneyBagMin = 5
	#Bank Currency Capacity
	#The max amount of currency the Bank can store.
	#Range: 0 ~ 99999999
	bankCurrencyCapacity = 1000000
	#Rich Money Bag Maximum Coins Amount
	#The maximum of the random amount of currency the Rich Money Bag gives.
	#Range: 0 ~ 10000
	richMoneyBagMax = 200
	#Cheap Money Bag Maximum Coins Amount
	#The maximum of the random amount of currency the Cheap Money Bag gives.
	#Range: 0 ~ 10000
	cheapMoneyBagMax = 25

[Wallet]
	#Render Wallet Currency Overlay
	#Enable this render an overlay on your game screen showing your Wallet stats.
	walletOverlay = true
	#Wallet Currency Overlay Position
	#The position of the screen of the Wallet overlay
	#The valid values are {TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT}
	walletOverlayPosition = "BOTTOM_RIGHT"
	#Wallet Currency Capacity
	#The max amount of currency the Wallet can store.
	#Range: 0 ~ 99999999
	walletCurrencyCapacity = 1000000

[Misc]
	#Trading Post Broadcasts
	#Disable this to disallow Players broadcasting their Trading Posts
	tradingPostBroadcasts = true
	#Speed Upgrade Cost Multiplier
	#This value is multiplied and added to the current cost of the Unit.
	#This value increases based on how many Speed Upgrades are in the slot.
	#Range: > 0
	speedUpgradeCostMultiplier = 0
	#Use Security
	#Disable this to allow everyone access to anyone's Blocks.
	useSecurity = true
	#Scaffold Max Height Teleport
	#0 to Disable. The max height you can teleport to the top or bottom of a scaffold.
	#Range: 0 ~ 256
	scaffoldMaxHeightTp = 256
	#Torch Placer Max Range
	#The max range the Torch Placer can place torches.
	#Range: 10 ~ 48
	torchPlacerMaxRange = 48
	#Blender Max Juice
	#The max height amount of juice the Blender can store.
	#Range: 0 ~ 1000000
	blenderMaxJuice = 1000
	#Trading Post Broadcast Delay
	#The amount of seconds before a Player can broadcasts their Trading Post.
	#Range: 0 ~ 3600
	tradingPostBroadcastDelay = 60

