
#Animal Spawn Settings
["Animal Spawn Settings"]
	#Bear Spawn Group Maximum Size
	#Range: > 1
	bear_max_spawn_size = 1
	#Piranha Spawn Group Maximum Size
	#Range: > 1
	piranha_max_spawn_size = 3
	#Rat Spawn Group Maximum Size
	#Range: > 1
	rat_max_spawn_size = 3
	#Wild Dog Spawn Group Minimum Size
	#Range: > 1
	wild_dog_min_spawn_size = 1
	#Rat Spawn Group Minimum Size
	#Range: > 1
	rat_min_spawn_size = 1
	#Piranha Spawn Chance Probability
	#Range: > 1
	piranha_chance = 10
	#Bear Spawn Group Minimum Size
	#Range: > 1
	bear_min_spawn_size = 1
	#Bear Max Y Spawn Height
	#Range: 1 ~ 256
	bear_max_y = 256
	#Rat Max Y Spawn Height
	#Range: 1 ~ 256
	rat_max_y = 256
	#Wild Dog Max Y Spawn Height
	#Range: 1 ~ 256
	wild_dog_max_y = 256
	#Wild Dog Spawn Chance Probability
	#Range: > 1
	wild_dog_chance = 10
	#Piranha Spawn Dimension Blacklist
	piranha_dimensions = []
	#Wild Dog Spawn Dimension Blacklist
	wild_dog_dimensions = []
	#Bears Spawn Only During Day
	bear_only_day_spawns = true
	#Bear Spawn Dimension Blacklist
	bear_dog_dimensions = []
	#Wild Dog Spawn Group Maximum Size
	#Range: > 1
	wild_dog_max_spawn_size = 3
	#Bear Spawn Chance Probability
	#Range: > 1
	bear_chance = 1
	#Piranha Spawn Group Minimum Size
	#Range: > 1
	piranha_min_spawn_size = 1
	#Rat Spawn Chance Probability
	#Range: > 1
	rat_chance = 10
	#Rat Spawn Dimension Blacklist
	rat_dimensions = []

#Animal Attack Settings
["Animal Attack Settings"]
	#Wild Dogs Attack Monsters
	wild_dog_should_attack_monsters = false
	#Rats Attack Everything (Except Rats)
	rat_should_attack_all = false
	#Piranhas Attack Everything (Except Piranhas)
	piranha_should_attack_all = false
	#Wild Dogs Attack Everything (Except Wild Dogs)
	wild_dog_should_attack_all = false
	#Rat Item Stealing Probability Bigger Numbers = Less Chance
	#Range: > 0
	rat_stealing_chance = 10
	#Piranhas Damage Boats Probablility
	#Range: > 0
	piranha_chance_to_damage_boats = 30
	#Piranhas Attack Monsters
	piranha_should_attack_monsters = false
	#Rats Attack Monsters
	rat_should_attack_monsters = false
	#Bears Attack Monsters
	bear_should_attack_monsters = false
	#Rats Steal Items
	rat_should_steal = false
	#Piranhas Damage Boats on Colliding
	piranha_should_damage_boats = true
	#Bears Attack Everything (Except Bears)
	bear_should_attack_all = false

