
[General]
	#When enabled, sends the player the area notifications in chat.
	sendChatMessages = false
	#The prefix of the message whenever a player leaves an area.
	leavePrefix = "Leaving "
	#When enabled, sends the player the area notifications in the HUD on screen.
	showHUDMessages = true
	#The radius in blocks around the player in which to check for area signs.
	#Range: 0 ~ 1000
	radiusAroundPlayerToCheckForSigns = 100
	#The prefix of the message whenever a player enters an area.
	joinPrefix = "Entering "
	#The suffix of the message whenever a player enters an area.
	joinSuffix = ""
	#The suffix of the message whenever a player leaves an area.
	leaveSuffix = ""
	#When enabled, gives signs without an area name a randomly chosen one from a preset list.
	giveUnnamedAreasRandomName = true

[Hud]
	#When enabled, only shows the areaname in the HUD. When disabled, the prefixes and suffices will also be used.
	HUDOnlyAreaName = false
	#The green RGB value for the HUD message.
	#Range: 0 ~ 255
	HUD_RGB_G = 200
	#The vertical offset (y coord) for the HUD message. This determines how far down the message should be on the screen. Can be changed to prevent GUIs from overlapping.
	#Range: 0 ~ 3000
	HUDMessageHeightOffset = 100
	#The red RGB value for the HUD message.
	#Range: 0 ~ 255
	HUD_RGB_R = 100
	#The blue RGB value for the HUD message.
	#Range: 0 ~ 255
	HUD_RGB_B = 50
	#The delay in ms after which the HUD message should fade out.
	#Range: 100 ~ 360000
	HUDMessageFadeDelayMs = 4000
	#Increases the font size of the text in the HUD message. If you change this value, make sure to test the different GUI scale settings in-game. 6.0 is considered large.
	#Range: 0.0 ~ 10.0
	HUD_FontModifier = 1.0

