
#Wires
[wires]
	#Connector max input (Energy transfer).
	#Range: > 0
	connector_max_input = 2048
	#Loss per block in gold wire (Not implemented, currently no loss).
	#Range: 0.0 ~ 0.5
	gold_wire_loss = 0.005
	#Connector internal capacity.
	#Range: > 0
	connector_capacity = 8196
	#Loss per block in copper wire (Not implemented, currently no loss).
	#Range: 0.0 ~ 0.5
	copper_wire_loss = 0.02
	#Connector max output (Energy transfer).
	#Range: > 0
	connector_max_output = 2048

#General Settings
[general]
	#Forge Energy conversion rate (in FE/t at max RPM).
	#Range: > 0
	fe_conversion = 80

#Electric Motor
[electric_motor]
	#Electric Motor internal capacity in FE.
	#Range: > 0
	motor_capacity = 16000
	#Electric Motor generated base stress (Not implemented).
	#Range: 0 ~ 256
	motor_stress = 16
	#Electric Motor max input in FE (Energy transfer not consumption).
	#Range: > 0
	motor_max_input = 8192
	#Electric Motor minimum RPM.
	#Range: 0 ~ 256
	motor_min_rpm = 32
	#Electric Motor maximum RPM.
	#Range: 1 ~ 256
	motor_max_rpm = 256

#Heater
[heater]
	#Enable Induction Heater when attached to a Furnace Engine.
	heater_furnace_engine_enable = false
	#Induction Heater internal capacity in FE.
	#Range: > 0
	heater_capacity = 16000
	#Induction Heater max input in FE (Energy transfer not consumption).
	#Range: > 0
	heater_max_input = 8192
	#Induction Heater normal consumption rate in FE/t.
	#Range: > 0
	heater_normal_consumption = 16
	#Induction Heater when attached to a Furnace Engine consumption rate in FE/t.
	#Range: > 0
	heater_furnace_engine_consumption = 400

#Alternator
[alternator]
	#Alternator efficiency relative to base conversion rate.
	#Range: 0.01 ~ 0.99
	generator_efficiency = 0.75
	#Alternator base stress impact.
	#Range: 0 ~ 1024
	generator_stress = 16
	#Alternator internal capacity in FE.
	#Range: > 0
	generator_capacity = 32000
	#Alternator max input in FE (Energy transfer not generation).
	#Range: > 0
	generator_max_output = 8192

#Rolling Mill
[rolling_mill]
	#Rolling Mill duration in ticks.
	#Range: > 0
	rolling_mill_processing_duration = 100
	#Rolling Mill base stress impact.
	#Range: 0 ~ 1024
	rolling_mill_stress = 16

