
#General bot Configuration
[generalSettings]
	#Whether or not the Bot should modify the channel description
	#Disabled by default becuase of discord limits
	botModifyDescription = false
	#The channel ID where the bot will be working in
	botChannel = "766707555585753088"
	#Enable checking for updates?
	#Notification will be shown after every server start in log when update is available
	enableUpdateChecker = false
	#The minimum release type for the update checker to notify
	#Allowed Values: alpha, beta, release
	updateCheckerMinimumReleaseType = "beta"
	#Allowed Values: WATCHING, PLAYING, LISTENING, DISABLED
	botPresenceType = "PLAYING"
	#Enable discord based whitelist?
	#This will override the link config!
	#To whitelist use !whitelist <uuid> in the bot DMs
	whitelist = false
	#Insert your Bot Token here!
	#DO NOT SHARE IT WITH ANYONE!
	botToken = "NzY1NjgwNjkwNTA2NjI5MTMw.X4YVtg.t_MuDn_wTaDN5V9Kf_1ahGAR_Is"
	#The Name of the Game
	#
	#PLACEHOLDERS:
	#%online% - Online Players
	#%max% - Maximum Player Amount
	botPresenceName = "%online% / %max%"
	#Show item information, which is visible on hover ingame, as embed in discord?
	sendItemInfo = true

#Webhook configuration
[webhook]
	#The avatar to be used for server messages
	serverAvatar = "https://raw.githubusercontent.com/mahjerion/Craft-to-Exile-Dissonance-Server/master/images/icon/Dissonance_Circle_Icon_1024.png"
	#Whether or not the bot should use a webhook (it will create one)
	serverName = "[Diss] - Tristram"
	#Whether or not the bot should use a webhook (it will create one)
	enableWebhook = true

#Discord linking configuration
[linking]
	#Role ID of an role an player should get when he links his discord account
	#Leave as 0 to disable
	linkedRole = "0"
	#Should discord linking be enabled?
	#If whitelist is on, this can not be disabled
	#DOES NOT WORK IN OFFLINE MODE!
	allow-linking = true

#Customize messages of this mod
[messages]
	#Chat message
	#PLACEHOLDERS:
	#%player% - The player´s name
	#%msg% - The chat message
	msgChatMessage = "%player%: %msg%"
	#When an /say command's message starts with this prefix it will not be sent to discord
	sayCommandIgnoredPrefix = "§c§o§9§k§r"
	#PLACEHOLDERS:
	#%player% - The player´s name
	msgPlayerLeave = "%player% left"
	#Message of the link method in normal mode
	linkMethodIngame = "`/discord link` ingame"
	#Send formatting codes from mc chat to discord
	#Has no effect when markdown <==> Minecraft is enabled
	formattingCodesToDiscord = false
	#Message to show while the server is starting
	#This will be edited to SERVER_STARTED_MSG when webhook is false
	msgServerStarting = "Server Starting..."
	#The message to print to discord when it was possible to detect a server crash
	#Will also be used in the channel description
	msgServerCrash = "Server Crash Detected :thinking:"
	#Sent when attempting to whitelist-link with an non uuid string
	#PLACEHOLDERS:
	#%arg% - The provided argument
	#%prefix% - Command prefix
	linkArgumentNotUUIDMessage = "Argument \"%arg%\" is not an valid UUID. Use `%prefix%whitelist <uuid>`"
	#Should /say output be sent to discord?
	enableSayOutput = true
	#Message shown to players who are not whitelisted using discord
	#No effect if discord whitelist is off
	msgWhitelist = "§cYou are not whitelisted.\nJoin the discord server for more information\nhttps://discord.gg/someserver"
	#PLACEHOLDERS:
	#%player% - The player´s name
	#%msg% - The death message
	msgPlayerDeath = "%player% %msg%"
	#Sent to the user when he linked his discord successfully
	#PLACEHOLDERS:
	#%player% - The player´s name
	linkFailedMessage = "Your account is now linked with %player%.\nUse /settings here to view and set some user-specific settings"
	#This message will be sent when the server was stopped
	msgServerStopped = "Server Stopped!"
	#Sent when user sucessfully updates an prersonal setting
	settingUpdatedSuccessfullyMessage = "Successfully updated setting!"
	#This is what will be displayed ingame when someone types into the bot´s channel
	#PLACEHOLDERS:
	#%user% - The username
	#%id% - The user ID
	#%msg% - The Message
	ingameDiscordMsg = "§6[§5DISCORD§6]§r <%user%> %msg%"
	#Sent when setting an personal setting fails
	settingUpdateFailedMessage = "Failed to set value :/"
	#Should tamed entity death be visible in discord?
	tamedDeathEnabled = false
	#PLACEHOLDERS:
	#%player% - The player´s name
	msgPlayerJoin = "%player% joined"
	#Sent when attempting to whitelist-link with an non uuid string
	invalidLinkNumberMessage = "Invalid link number! Use `/discord link` ingame to get your link number"
	#Supports MulitLined messages using \n
	#PLACEHOLDERS:
	#%player% - The player´s name
	#%name% - The advancement name
	#%desc% - The advancement description
	msgAdvancement = "%player% just gained the advancement **%name%**\\n_%desc%_"
	#Message sent when ignoring Discord messages
	msgIgnoreIgnore = "You are now ignoring Discord messages!"
	#Message of the link method in whitelist mode
	linkMethodWhitelist = "`%prefix%whitelist <uuid>` here"
	#A list of blacklisted modids
	#Adding one will prevent the mod to send messages to discord using forges IMC system
	imcModIdBlacklist = "[\"examplemodid\"]"
	#Sent when an already linked user attempts to link an account
	#PLACEHOLDERS:
	#%player% - The player´s name
	alreadyLinkedMessage = "Your account is already linked with %player%"
	#This message will edited in / sent when the server finished starting
	msgServerStarted = "Server Started!"
	#PLACEHOLDERS:
	#%player% - The player´s name
	#NOTE: This is currently not implemented because mixins are not working in 1.15!
	msgPlayerTimeout = "%player% timed out!"
	#Sent to the user when he linked his discord successfully
	#PLACEHOLDERS:
	#%player% - The player´s name
	linkSuccessfulMessage = "Your account is now linked with %player%.\nUse /settings here to view and set some user-specific settings"
	#Sent when attempting to use personal commands while not linked
	#PLACEHOLDERS:
	#%method% - The currently enabled method for linking
	accountNotLinkedMessage = "Your account is not linked! Link it first using %method%"
	#Header of the personal settings list
	NANLinkNumberMessage = "Personal Settings list:"
	#Prevent sending MC color codes from Discord to server chat?
	#Does not disable Markdown to minecraft conversion!
	preventDiscordFormattingCodesToMC = false
	#The format of the uptime command and %uptime% placeholder
	#For more help with the formatting visit https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DurationFormatUtils.html
	#Note: The use of precise values like seconds might cause rate limits
	uptimeFormat = "dd 'days' HH 'hours' mm 'minutes'"
	#Enable formatting conversion (Markdown <==> Minecraft)
	convertFormatting = true
	#Should /me output be sent to discord?
	enableMeOutput = true
	#Message sent when unignoring Discord messages
	msgIgnoreUnignore = "You are no longer ignoring Discord messages!"
	#Error message when providing an invalid personal setting name
	invalidPSettingsKeyMsg = "This settings value is `%bool%`"

#Configuration for built-in discord commands
[dc-commands]
	#The Role ID of your Admin Role
	adminRoleId = "726732089344524299"
	#Set to true to require an space after the prefix
	prefixSpace = false
	#The header for 'list'
	#PLACEHOLDERS:
	#%amount% - The amount of players online
	msgListHeader = "There are %amount% players online:"
	#Enable help command?
	#Disabling also removes response when you entered an invalid command
	#Requires server restart
	enableHelpCommand = true
	#You MUST op this UUID in the ops.txt or many commands won't work!!
	senderUUID = "8d8982a5-8cf9-4604-8feb-3dd5ee1f83a3"
	#The prefix of the commands like list
	prefix = "/"
	#Header of the help command
	helpHeader = "Your available commands in this channel:"
	#Message if a player provides too many arguments
	msgTooManyArgs = "Too many arguments"
	#Enable the list command in discord
	#Requires server restart
	enableListCommand = true
	#The header for 'list' when one player is online
	msgListOne = "There is 1 player online:"
	#Add your Custom commands to this JSON
	#You can copy-paste it to https://jsoneditoronline.org  Make sure when pasting here, that the json is NOT mulitlined.
	#You can click on "Compact JSON Data" on the website
	#NOTE: The JSON string must be escaped. You can use this website to escape or unescape: https://www.freeformatter.com/java-dotnet-escape.html
	#NOTE 2: You MUST op the uuid set at SENDER_UUID in the ops.txt !!!
	#
	#mcCommand   -   The command to execute on the server
	#adminOnly   -   True: Only allows users with the Admin role to use this command. False: @everyone can use the command
	#description -   Description shown in /help
	#aliases     -   Aliases for the command in a string array
	#useArgs     -   Shows argument text after the command
	#argText     -   Defines custom arg text. Default is <args>
	#channelIDs  -   Allows you to set specific text channels outside of the server channel to use this command (make it an string array), Set to ["00"] to allow from all channels
	jsonCommands = "{\"kick\":{\"adminOnly\":true,\"mcCommand\":\"kick\",\"description\":\"Kicks a player from the server\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e [reason]\"},\"stop\":{\"adminOnly\":true,\"mcCommand\":\"stop\",\"description\":\"Stops the server\",\"aliases\":[\"shutdown\"],\"useArgs\":false},\"kill\":{\"adminOnly\":true,\"mcCommand\":\"kill\",\"description\":\"Kills a player\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e\"},\"tps\":{\"adminOnly\":false,\"mcCommand\":\"forge tps\",\"description\":\"Displays TPS\",\"useArgs\":false}}"
	#Set to true to enable the "Unknown Command" message in all channels
	enableUnknownCommandEverywhere = false
	#Custom Channel ID list for the list command. Set to 00 to allow usage from everywhere and to 0 to allow usage from the bots default channel
	helpCmdChannel = "0"
	#Set to false to completely disable the "Unknown Command" message
	enableUnknownCommandMsg = true
	#Message if a player can not be found
	#PLACEHOLDERS:
	#%player% - The player´s name
	msgPlayerNotFound = "Can not find player \"%player%\""
	#Message sent when user does not have permission to run a command
	msgNoPermission = "You don´t have permission to execute this command!"
	#The message for 'list' when no player is online
	msgListEmpty = "There is no player online..."
	#Message if a player provides less arguments than required
	msgNotEnoughArgs = "Not enough arguments"
	#Message sent when an invalid command was typed
	#PLACEHOLDERS:
	#%prefix% - Command prefix
	msgUnknownCommand = "Unknown command, try `%prefix%help` for a list of commands"
	#Enable the iptime command in discord
	#Requires server restart
	enableUptimeCommand = true

#Configurate the /discord command useable ingame
[mc-command]
	#The url to open when clicking the /discord command text
	dcCmdURL = "http://discord.gg/myserver"
	#The message displayed when typing /discord in the server chat
	dcCmdMsg = "Join our discord! http://discord.gg/myserver"
	#The message shown when hovering the /discord command message
	dcCmdMsgHover = "Click to open the invite url"
	#Enable the /discord command?
	dcCmdEnabled = true

#Configure Advanced features like moving specific message types to different channels
[advanced]
	#Custom channel for description
	#Leave empty to use default channel
	channelDescriptionID = ""
	#Custom channel ID for server specific messages (like Join/leave)
	#Leave empty to use default channel
	serverChannelID = ""
	#Custom channel ID for death messages
	#Leave empty to use default channel
	deathChannelID = ""
	#Custom channel where messages get sent to minecraft
	#Leave empty to use default channel
	chatInputID = ""
	#Custom channel for for ingame messages
	#Leave empty to use default channel
	chatOutputID = ""

