
#General Settings
[general]
	#Enables the dungeon crawl developer tools.
	enable_tools = false
	#Enables extended debug logging to help detecting potential errors. This is enabled by default.
	extended_debug = true

#World Generation Settings
["world generation"]
	#Whether falling blocks like sand or gravel should drop down after being placed during dungeon generation.
	tick_falling_blocks = true
	#Makes the entire dungeon solid, preventing caves, ravines, etc... from interfering with the dungeon.
	solid = false

#Dungeon Placement Settings
["dungeon placement"]
	#The average distance between the dungeons in chunks. This has to be higher than the separation!
	#Range: 8 ~ 8192
	spacing = 24
	#The minimum distance between the dungeons in chunks. This has to be lower than the spacing!
	#Range: 8 ~ 8192
	separation = 12

#Dungeon Settings
[dungeon]
	#Whether the dungeons should have secret rooms or not.
	secret_rooms = true
	#When enabled, the hell stage will be built with blocks from the overworld, not from the nether.
	no_nether_stuff = false
	#Whether loot tables of certain spawner entities should be overwritten. If this enabled, wither skeletons from dungeon spawners will never drop skulls. Changing this will not affect already generated dungeons.
	overwrite_entity_loot_tables = true
	#Whether custom mob spawners with equipment, etc.. should be used.
	custom_spawners = true
	#The activation range for the spawners in the dungeons
	#Range: 1 ~ 64
	spawner_activation_range = 12
	#Whether mobs from spawners should despawn naturally or not.
	natural_despawn = true
	#The number of different entities per spawner. Increasing the number increases the diversity of the monster equipment.
	#Range: 1 ~ 128
	spawner_entities = 6

