#allow horses to swim
doHorsesSwim = false

#Blacklist
[blacklist]
	#list of resourcelocations in string form
	blacklist = ["minecraft:tnt", "corpse:corpse", "farmingforblockheads:merchant", "minecraft:trader_llama"]

#Whitelist
[whitelist]
	#list of resourcelocations in string form
	whitelist = ["minecraft:horse"]

