
[General]
	#Determines whether a locker's delivery radius will ignore a package's delivery location's Y-coordinate.
	lockerDeliveryRadiusIgnoresY = false
	#Determines whether package deliveries will be logged in the console.
	logDeliveries = false
	#The maximum distance that packages can be delivered over. Set to -1 for no distance limit.
	#Range: -1 ~ 1000000
	maxDeliveryDistance = -1
	#Packages with delivery locations within this radius of a locker will be delivered to the locker.
	#Range: 0 ~ 500
	lockerDeliveryRadius = 10

