
#GENERAL SETTINGS
[GENERAL]
	#Enable direct Flesh to Combined Flesh (Smoker OR Furnace enabled is required)
	babyMode = false
	#Enable Furnace recipe. This OR Smoker recipe is required.
	furnaceRecipe = false
	#Enable Smoker recipe. This OR Furnace recipe is required.
	smokerRecipe = true
	#Enable easier recipe
	easyMode = false
	#Enable harder (normal) recipe
	hardMode = true
	#Enable Simple recipe (5 rotten flesh in X = 1 Combined Flesh)
	simpleRecipe = false
	#Enable super easy mode. 1 Rotten Flesh = 1 Leather. (Seriously? Do you hate a challenge that much???)
	EZMode = false

