
[client]
	#Show item tags and nbt in advanced tooltips
	debugTooltip = true
	#Max line width shown in description of tooltips
	#Range: > 50
	tooltipWrapWidth = 100
	#Allowed values: vanilla, kiwi
	debugTooltipNBTFormatter = "vanilla"
	contributorEffect = ""
	#Tooltips require pressing shift to be shown
	tooltipRequiresShift = false

