
#Server and Client side changes.
[common]
	#If true, lava monsters do not require a source block to spawn.
	flowingLava = false
	#Allows you to choose which dimensions the Lava Monster spawns in. Add dimensions by their registry name/id, and separate them with commas, no spaces.
	dimensionWhitelist = "minecraft:the_nether,goodnightsleep:nightmare"
	#Number of fireballs shot with each attack.
	attackShots = 1
	#The number of ticks between each lava monster spawn attempt.
	spawnFrequency = 200
	#If true, lava monsters will not spawn above layer 16.
	depthHazard = true
	#Lava monsters' maximum health.
	monsterHealth = 16.0
	#The amount of armor lava monsters have.
	monsterArmor = 0.0
	#Ticks between each fireball shot in an attack.
	attackSpacing = 10
	#Ticks a monster must wait after attacking before it can start winding up again.
	attackCooldown = 80
	#Ticks it takes before a monster can start an attack.
	attackWindup = 60
	#The chance for a lava monster spawn attempt to be successful.
	spawnChance = 0.05
	#If true, lava monsters will be able to spawn in lava one block deep.
	shallowLava = false

