
[Stronghold]
	#
	# Minimum Y height that normal stronghold's starting point can spawn at.
	# Default is 50.
	# Note: Strongholds will spawn between min and max y height set in config.
	# Setting this to below min height config will make strongholds spawn only at min height.
	#Range: 0 ~ 255
	normalStrongholdMaxHeight = 50
	#
	# How often Silverfish Blocks will generate in Strongholds as a percentage.
	# Note: Mossy Stone Bricks block cannot be infected by Silverfish
	# 0 for no Silverfish Blocks and 100 for max spawnrate.
	#Range: 0.0 ~ 100.0
	silverfishSpawnrateSH = 0.8
	#
	# Minimum Y height that normal stronghold's starting point can spawn at. 
	#Default is 0.
	# Note: Strongholds will spawn between min and max y height set in config.
	#
	#Range: 0 ~ 255
	normalStrongholdMinHeight = 0
	#
	# Make Mob Spawners generate in rooms other than the Portal Room in Strongholds.
	# Note: Spawners in Portal Room will always remain.
	allowExtraSpawnersSH = true
	#
	# Minimum Y height that Nether stronghold's starting point can spawn at. 
	#Default is 35.
	# Note: Strongholds will spawn between min and max y height set in config.
	#
	#Range: 0 ~ 255
	netherStrongholdMinHeight = 35
	#
	# How rare are Strongholds.
	# 1 for spawning in most chunks and 1001 for no spawn.
	#Range: 1 ~ 1001
	strongholdSpawnrate = 85
	#
	# Use vanilla Stronghold instead of using this mod's modded version.
	# Note: The other Stronghold configs here will have no effect on vanilla Strongholds. 
	# WARNING: Nether Strongholds will be turned off too when this option is on.
	useVanillaStronghold = false
	#
	# Allow Nether-styled Strongholds to spawn in Nether category biomes.
	# Note: Eyes of Ender will work and show the closest Nether Stronghold too.
	allowNetherStronghold = true
	#
	# Allow Stonebrick styled Stronghold to generate in non-Nether biomes.
	allowStonebrickStronghold = true
	#
	# How large the Stronghold is on average as a percentage.
	# Note: The Stonghold is much larger by default. To get something 
	# closer to vanilla stronghold size, use the value of 60.
	# 10 for supertiny Strongholds and 2000 for supermassive Strongholds.
	#Range: 10.0 ~ 2000.0
	strongholdSizeSH = 100.0
	#
	# Minimum Y height that Nether stronghold's starting point can spawn at. 
	#Default is 40.
	# Note: Strongholds will spawn between min and max y height set in config.
	# Setting this to below min height config will make strongholds spawn only at min height.
	#Range: 0 ~ 255
	netherStrongholdMaxHeight = 40
	#
	# Controls whether loot chests spawn or not in the Stronghold.
	lootChestsSH = true

