
[Mineshaft]
	#
	# Controls whether loot chests spawn or not in modded Mineshafts.
	lootChestsMS = true
	#
	# Add the custom Mineshafts to modded biomes of the same categories/type.
	addMineshaftsToModdedBiomes = false

	[Mineshaft."Max height"]
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 50.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		endMineshaftMaxHeight = 40
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 50.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		desertMineshaftMaxHeight = 50
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 50.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		taigaMineshaftMaxHeight = 50
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 50.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		swampAndDarkForestMineshaftMaxHeight = 50
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 50.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		stoneMineshaftMaxHeight = 50
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 50.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		icyMineshaftMaxHeight = 50
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 25.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		oceanMineshaftMaxHeight = 25
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 50.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		birchMineshaftMaxHeight = 50
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 22.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		netherMineshaftMaxHeight = 22
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 50.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		jungleMineshaftMaxHeight = 50
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 50.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		savannaMineshaftMaxHeight = 50

	[Mineshaft."Min height"]
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 5.
		# Note: The mineshaft will spawn between min and max y height set in config.
		#
		#Range: 5 ~ 255
		netherMineshaftMinHeight = 5
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 5.
		# Note: The mineshaft will spawn between min and max y height set in config.
		#
		#Range: 5 ~ 255
		oceanMineshaftMinHeight = 5
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 5.
		# Note: The mineshaft will spawn between min and max y height set in config.
		#
		#Range: 5 ~ 255
		savannaMineshaftMinHeight = 5
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 5.
		# Note: The mineshaft will spawn between min and max y height set in config.
		#
		#Range: 5 ~ 255
		icyMineshaftMinHeight = 5
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 5.
		# Note: The mineshaft will spawn between min and max y height set in config.
		#
		#Range: 5 ~ 255
		jungleMineshaftMinHeight = 5
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 30.
		# Note: The mineshaft will spawn between min and max y height set in config.
		#
		#Range: 5 ~ 255
		endMineshaftMinHeight = 30
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 0.
		# Note: The mineshaft will spawn between min and max y height set in config.
		# Setting this to below min height config will make mineshaft spawn only at min height.
		#Range: 5 ~ 255
		birchMineshaftMinHeight = 5
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 5.
		# Note: The mineshaft will spawn between min and max y height set in config.
		#
		#Range: 5 ~ 255
		stoneMineshaftMinHeight = 5
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 5.
		# Note: The mineshaft will spawn between min and max y height set in config.
		#
		#Range: 5 ~ 255
		desertMineshaftMinHeight = 5
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 5.
		# Note: The mineshaft will spawn between min and max y height set in config.
		#
		#Range: 5 ~ 255
		taigaMineshaftMinHeight = 5
		#
		# Minimum Y height that this mineshaft can spawn at. Default is 5.
		# Note: The mineshaft will spawn between min and max y height set in config.
		#
		#Range: 5 ~ 255
		swampAndDarkForestMineshaftMinHeight = 5

	[Mineshaft.Spawnrate]
		#
		# Controls how often Mineshafts will spawn. 1000 is max spawnrate.
		# 
		# Replace Mineshafts in Swamps and Dark Forests with a swampy/dark oak themed Mineshaft.
		# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		swampAndDarkForestMineshaftSpawnrate = 40
		#
		# Controls how often Mineshafts will spawn. 1000 is max spawnrate.
		# 
		# Replace Mineshafts in Jungle biomes with a Jungle themed Mineshaft.
		# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		jungleMineshaftSpawnrate = 40
		#
		# Controls how often Mineshafts will spawn. 1000 is max spawnrate.
		# 
		# Replace Mineshafts in Taiga biomes with a Taiga themed Mineshaft. Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		taigaMineshaftSpawnrate = 40
		#
		# Controls how often Mineshafts will spawn. 1000 is max spawnrate.
		# 
		# Replace Mineshafts in Birch biomes with a Birch themed Mineshaft.
		# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		birchMineshaftSpawnrate = 40
		#
		# Controls how often Mineshafts will spawn.
		# 
		# Add Nether themed Mineshafts to Nether biomes.0 for no Mineshafts and 1000 for max spawnrate.
		#Range: 0 ~ 1000
		netherMineshaftSpawnrate = 40
		#
		# Controls how often Mineshafts will spawn. 1000 is max spawnrate.
		# 
		# Replace Mineshafts in Desert biomes with a Desert themed Mineshaft.
		# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		desertMineshaftSpawnrate = 40
		#
		# Controls how often Mineshafts will spawn. 1000 is max spawnrate.
		# 
		# Replace Mineshafts in Ocean biomes with an Ocean themed Mineshaft.
		# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		oceanMineshaftSpawnrate = 40
		#
		# Controls how often Mineshafts will spawn. 1000 is max spawnrate.
		# 
		# Replace Mineshafts in Savanna biomes with a Savanna themed Mineshaft.
		# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		savannaMineshaftSpawnrate = 40
		#
		# Controls how often Mineshafts will spawn.
		# 
		# Add End themed Mineshafts to End biomes outside the Enderdragon island.0 for no Mineshafts and 1000 for max spawnrate.
		#Range: 0 ~ 1000
		endMineshaftSpawnrate = 40
		#
		# Controls how often Mineshafts will spawn. 1000 is max spawnrate.
		# 
		# Replace Mineshafts in Mountain (Extreme Hills) biomes with a Stone themed Mineshaft.
		# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		stoneMineshaftSpawnrate = 40
		#
		# Controls how often Mineshafts will spawn. 1000 is max spawnrate.
		# 
		# Replace Mineshafts in Snowy/Icy biomes with an Ice themed Mineshaft.
		# Note: Snowy Taiga Biomes will get Ice Mineshaft instead of Taiga theme.
		# Note: Vanilla Mineshafts will start spawning when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		icyMineshaftSpawnrate = 40

