
[Villages]
	#
	# Add the custom villages to modded biomes of the same categories/type.
	addVillagesToModdedBiomes = false

	[Villages.Spawnrate]
		#
		# How rare are Badlands Villages in Badland biomes.
		#
		#  1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		badlandsVillageSpawnrate = 17
		#
		# How rare are Dark Forest Villages in Dark Forest biomes.
		#
		#  1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		darkForestVillageSpawnrate = 24
		#
		# How rare are Swamp Villages in Swamp biomes.
		#
		#  1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		swampVillageSpawnrate = 24
		#
		# How rare are Jungle Villages in Jungle biomes.
		#
		#  1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		jungleVillageSpawnrate = 26
		#
		# How rare are Giant Taiga Villages in Giant Taiga biomes.
		#
		#  1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		giantTaigaVillageSpawnrate = 24
		#
		# How rare are Birch Villages in Birch biomes.
		#
		#  1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		birchVillageSpawnrate = 24
		#
		# How rare are Mountains Villages in Mountains biomes.
		#
		#  1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		mountainsVillageSpawnrate = 24

