
["Blaze Features"]
	#The amount of damage done when pushed by a Blaze.
	#Range: 0.0 ~ 32767.0
	Blaze_PushDamage = 1.0
	#The type of explosion that occurs when a Blaze dies:
	#NONE = no effect other than damage to player
	#BREAK = break blocks in range; broken blocks drop items
	#DESTROY = destroy blocks and items
	#Allowed Values: NONE, BREAK, DESTROY
	Blaze_DeathExplosionType = "NONE"
	#Entities which count as Blaze entities
	Blaze_Entities = ["minecraft:blaze"]
	#Set to false to disable all Blaze features.
	Blaze_FeaturesEnabled = true
	#Set to false to prevent Blazes from pushing attackers away.
	Blaze_PushAttackersAway = true
	#Explosion strength which Blazes create on death.
	#Set to 0 to disable this feature 
	#Range: 0.0 ~ 32767.0
	Blaze_DeathExplosionStrength = 1.0
	#Set to false to prevent Blazes from igniting entities which touch their hitbox.
	Blaze_FlameTouch = true

["Hostile Horse Features"]
	#Chance (1 in X) that a random skeleton or zombie starts riding unmounted hostile horses around it.
	#Range: 0 ~ 32767
	HostileHorse_RiderChance = 3
	#Set this to false to prevent undead horses from burning in sunlight (as long as they have no rider).
	HostileHorse_DaylightBurn = true
	#Set to false to disable all hostile horse features.
	HostileHorse_FeaturesEnabled = true
	#Set to false to prevent undead horses summoned by this mod from despawning.
	HostileHorse_CanDespawn = true
	#Entities which count as hostile horses.
	HostileHorse_Entities = ["minecraft:zombie_horse", "minecraft:skeleton_horse"]

["Spider Features"]
	#Chance (1 in X) that a randomly spawned entity from the RiderEntities list can start riding on random spiders.
	#Set to 0 to disable this feature.
	#Range: 0 ~ 32767
	Spider_StartRidingChance = 10
	#Set this to false to prevent spiders from creating webs on slowed targets.
	Spider_SlownessWeb = true
	#Chance (1 in X) for a spider to spawn with another entity riding it.
	#Set to 0 to disable this feature.
	#Range: 0 ~ 32767
	Spider_SpawnedRiderChance = 10
	#Chance (1 in X) for a spider to apply the slowness effect on attack.
	#Set to 0 to disable this feature.
	#Range: 0 ~ 32767
	Spider_SlownessChance = 1
	#The fall damage spiders take is multiplied by this value (0.0 means no fall damage, 1.0 means normal full damage).
	#Range: 0.0 ~ 1.0
	Spider_IgnoreFallDamageMultiplier = 0.0
	#Entities which count as Spiders.
	Spider_Entities = ["minecraft:spider", "minecraft:cave_spider"]
	#Enable this to use all Spider features.
	Spider_FeaturesEnabled = true
	#Duration in seconds of the applied slowness effect.
	#Range: 0 ~ 32767
	Spider_SlownessDuration = 10
	#Entities which may ride on spiders.
	Spider_RiderEntities = ["minecraft:zombie", "minecraft:skeleton", "minecraft:witch"]

["Zombie Features"]
	#Chance (1 in X) that a zombie spawns riding a zombie horse.
	#Set to 0 to disable this feature.
	#Range: 0 ~ 32767
	Zombie_HorseChance = 20
	#Chance (1 in X) for a newly spawned zombie to become a Zombie Champion
	#Range: 0 ~ 32767
	Zombie_ChampionChance = 200
	#Chance (1 in X) for a zombie to leap to the target.
	#Set to 0 to disable this feature.
	#Range: 0 ~ 32767
	Zombie_LeapChance = 4
	#Duration in seconds of the applied hunger effect.
	#Range: 0 ~ 32767
	Zombie_HungerDuration = 10
	#Entities which count as Zombies.
	Zombie_Entities = ["minecraft:zombie", "minecraft:zombie_villager", "minecraft:husk", "minecraft:zombie_pigman"]
	#Enable this to use all Zombie features.
	Zombie_FeaturesEnabled = true
	#A list of names to be used by Zombie Champions.
	Zombie_ChampionNames = ["Zombie King", "Flesh King", "Dr. Zomboss", "Azog", "Zon-Goku", "Z0mb3y"]
	#Blocks which can be destroyed by zombies if they have no attack target.
	#Delete all lines to disable this feature.
	Zombie_BreakBlocks = ["minecraft:dirt", "minecraft:grass", "minecraft:planks", "minecraft:log", "minecraft:sand", "minecraft:wooden_slab", "minecraft:chest", "minecraft:wool", "minecraft:carrots", "minecraft:potatoes", "minecraft:wheat", "minecraft:nether_wart", "minecraft:beetroots", "minecraft:pumpkin_stem", "minecraft:melon_stem", "minecraft:pumpkin", "minecraft:hay_block", "minecraft:torch"]
	#Set this to false to prevent baby zombies from burning in sunlight.
	Zombie_BabyBurns = true
	#Set this to true to make all zombies burn in sunlight even if they wear a helmet.
	Zombie_HelmetBurn = true
	#Minimum Y position above which zombie horses may spawn.
	#Range: 0 ~ 32767
	Zombie_HorseMinY = 63
	#Amount of blocks the zombie jumps on leap attack.
	#Range: 0.0 ~ 127.0
	Zombie_LeapHeight = 0.5
	#Chance (1 in X) for a zombie to apply the hunger effect on attack.
	#Set to 0 to disable this feature.
	#Range: 0 ~ 32767
	Zombie_HungerChance = 4

["Zombie Pigman Features"]
	#Block radius in which zombie pigman get aggressive if the player breaks blocks.
	#Range: 1 ~ 32767
	ZombiePigman_AggressiveBlockRange = 20
	#Entities which count as Zombie Pigmen.
	ZombiePigman_Entities = ["minecraft:zombie_pigman"]
	#Enable this to use all Zombie Pigman features.
	ZombiePigman_FeaturesEnabled = true
	#Set to false to prevent zombie pigman from getting aggressive if the player touches its hitbox.
	ZombiePigman_AggressiveTouch = false
	#The range at which zombie pigmen will be aggressive to the player..
	#Range: 0 ~ 32767
	ZombiePigman_AggressiveRange = 10
	#Set to true for zombie pigmen to always be aggressive.
	ZombiePigman_AlwaysAggressive = false
	#Chance (1 in X) that a zombie pigman gets aggressive if the player breaks nearby blocks.
	#Range: 0 ~ 32767
	ZombiePigman_AggressiveBlockChance = 10

